#!/bin/bash

#echo 'Running stringtie'
tmp_filename="stringtie_tmp_$$.txt"

#rm -f $tmp_filename
touch $tmp_filename

echo -e "@HD\tVN:1.0\tSO:coordinate" >> $tmp_filename
echo -e "@SQ\tSN:chrX\tLN:156040895" >> $tmp_filename

while read line
do
    echo -e $line >> $tmp_filename
done

sed -i -e 's/ /\t/g' $tmp_filename
#cat $tmp_filename
samtools sort -T temp -O sam -o ${tmp_filename}".sam" $tmp_filename
stringtie -p 8 ${tmp_filename}".sam"

#$tmp_filename
